IF(CGAL_Qt4_FOUND AND QT4_FOUND AND OPENGL_FOUND AND QGLVIEWER_FOUND)
	SET(QGLVIEWER_PROGRAM_PATHS 
		${QGLVIEWER_INCLUDE_DIR}
		${QGLVIEWER_INCLUDE_DIR}/bin
		${QGLVIEWER_INCLUDE_DIR}/bin/release
		${QGLVIEWER_INCLUDE_DIR}/release
		${QGLVIEWER_LIBRARY_RELEASE}
		/usr/bin
		/usr/local/bin
		/opt/local/bin
	)
	SET(QT_PROGRAM_PATHS 
		${QT_BINARY_DIR}
		${QT_BINARY_DIR}/bin
		${QT_BINARY_DIR}/bin/release
		${QT_BINARY_DIR}/release
		${QT_LIBRARY_DIR}
		/usr/bin
		/usr/local/bin
		/opt/local/bin
	)

	FIND_FILE(QGLVIEWER_LIB_DLL
		NAMES QGLViewer2.dll
		PATHS ${QGLVIEWER_PROGRAM_PATHS}
	)
	FIND_FILE(QT_QGLVIEWER_CORE_LIB_DLL 
		NAMES QtCore4.dll
		PATHS ${QT_PROGRAM_PATHS}
	)
	FIND_FILE(QT_QGLVIEWER_GUI_LIB_DLL 
		NAMES QtGui4.dll
		PATHS ${QT_PROGRAM_PATHS}
	)
	FIND_FILE(QT_QGLVIEWER_OPENGL_LIB_DLL 
		NAMES QtOpenGL4.dll
		PATHS ${QT_PROGRAM_PATHS}
	)
	FIND_FILE(QT_QGLVIEWER_XML_LIB_DLL 
		NAMES QtXml4.dll
		PATHS ${QT_PROGRAM_PATHS}
	)

	INSTALL_FILES(/bin FILES ${QGLVIEWER_LIB_DLL})
	INSTALL_FILES(/bin FILES ${QT_QGLVIEWER_CORE_LIB_DLL})
	INSTALL_FILES(/bin FILES ${QT_QGLVIEWER_GUI_LIB_DLL})
	INSTALL_FILES(/bin FILES ${QT_QGLVIEWER_OPENGL_LIB_DLL})
	INSTALL_FILES(/bin FILES ${QT_QGLVIEWER_XML_LIB_DLL})
ENDIF (CGAL_Qt4_FOUND AND QT4_FOUND AND OPENGL_FOUND AND QGLVIEWER_FOUND)